"""Generate evidence-linked presentation and formal PDF report after a completed run."""
from __future__ import annotations
from pathlib import Path
import pandas as pd
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib import colors
from pptx import Presentation
from pptx.util import Inches, Pt

def build(root: Path, leaderboard: pd.DataFrame, test: dict, run_id: str) -> None:
    """Create PPTX/PDF documents only from actual run artifacts. Args: data/run ID. Returns: None."""
    reports=root/'reports'; pres=root/'presentation'; reports.mkdir(exist_ok=True); pres.mkdir(exist_ok=True)
    winner=leaderboard.iloc[0] if len(leaderboard) else None; styles=getSampleStyleSheet()
    story=[Paragraph('Medical Insurance Claim Fraud Detection',styles['Title']),Paragraph('AI-Driven Claim Verification and Explainable Fraud Detection',styles['Heading2']),Paragraph('Traditional Machine Learning with Full Benchmarking',styles['Heading2']),Spacer(1,12),Paragraph('IIIT Dharwad | B.Tech Data Science and AI',styles['Normal']),Paragraph('B Varshith (23BDS011) | M Jagadeshwar (23BDS033) | J Ganesh (23BDS024)',styles['Normal']),Paragraph('Faculty Adviser: Prof. Ramesh Athe',styles['Normal']),Paragraph(f'Run identifier: {run_id}',styles['Normal']),Spacer(1,12),Paragraph('Ethics statement: This project uses synthetic data and supports human investigator triage; it does not automate claim denial.',styles['BodyText']),Spacer(1,12),Paragraph('Results',styles['Heading1'])]
    if winner is not None: story += [Paragraph(f"Selected model: {winner['model_key']}; validation PR-AUC: {winner['val_pr_auc']:.4f}.",styles['BodyText']),Paragraph(f"Test PR-AUC: {test.get('pr_auc','not available')}; operating threshold: {test.get('threshold','not available')}.",styles['BodyText'])]
    table=[list(leaderboard[['model_key','family','val_pr_auc','val_roc_auc','val_f2']].head(12).columns)]+leaderboard[['model_key','family','val_pr_auc','val_roc_auc','val_f2']].head(12).round(4).astype(str).values.tolist()
    t=Table(table,repeatRows=1); t.setStyle(TableStyle([('BACKGROUND',(0,0),(-1,0),colors.HexColor('#006D77')),('TEXTCOLOR',(0,0),(-1,0),colors.white),('GRID',(0,0),(-1,-1),.25,colors.grey)])); story.append(t)
    story += [Spacer(1,12),Paragraph('Methodology',styles['Heading1']),Paragraph('Claims are group-stratified by claimant into train, validation, and test partitions. Preprocessing is fitted on training data only. The model selection policy prioritizes validation PR-AUC, then F2 and simplicity. Test evaluation is performed only after selection.',styles['BodyText']),Paragraph('Limitations',styles['Heading1']),Paragraph('Synthetic labels encode documented patterns and cannot establish real-world effectiveness. Fairness and calibration results are dataset-specific. A human investigator remains the decision owner.',styles['BodyText'])]
    for name in ['approach_1_project_report.pdf','approach_1_ieee_paper.pdf']:
        SimpleDocTemplate(str(reports/name),pagesize=A4).build(story)
    deck=Presentation(); deck.slide_width=Inches(13.333)
    slides=[('Medical Insurance Claim Fraud Detection','Traditional Machine Learning with Full Benchmarking\nIIIT Dharwad\nB Varshith (23BDS011) | M Jagadeshwar (23BDS033) | J Ganesh (23BDS024)\nFaculty Adviser: Prof. Ramesh Athe'),('Problem Statement','Binary decision support: Is a submitted claim fraudulent?\nOutput: probability plus yes/no triage recommendation.'),('Data and Ethics','Synthetic Indian-context claims only.\nNo personal data. Human investigators retain adjudication authority.'),('Benchmark Protocol','Group-stratified 70/15/15 split; validation PR-AUC is primary; test set used after selection.'),('Leaderboard',leaderboard[['model_key','val_pr_auc','val_f2']].head(8).round(4).to_string(index=False) if len(leaderboard) else 'Run pipeline to populate results.'),('Responsible AI','False negatives can pay fraud; false positives delay genuine claims. Flagged claims receive human review and explanation.'),('Conclusion',f"Run {run_id}. Selected model: {winner['model_key'] if winner is not None else 'pending'}.")]
    for title,body in slides:
        s=deck.slides.add_slide(deck.slide_layouts[1]); s.shapes.title.text=title; tf=s.placeholders[1].text_frame; tf.text=body
        for p in tf.paragraphs: p.font.size=Pt(20)
        s.notes_slide.notes_text_frame.text='Speaker note: Present only results generated by the pipeline. Explain that the system supports, rather than replaces, human investigation.'
    deck.save(pres/'approach_1_traditional_ml.pptx')
